Add a second dbServer and set default engine to RocksDB

diff --git a/scripts/tmux_starter b/scripts/tmux_starter
--- a/scripts/tmux_starter
+++ b/scripts/tmux_starter
@@ -181,24 +181,25 @@ suite_local_cluster(){
     shift 1
     local args="$@"
     local args_default=( '-c' 'none'
-						 '--log.force-direct' 'true'
+						 '--log.force-direct' 'false'
 						 '--log.level' 'INFO'
 						 '--server.authentication' 'false'
 						 '--javascript.startup-directory' './js'
 						 '--javascript.module-directory' './enterprise/js'
+                         '--server.statistics' 'true'
+                         '--server.storage-engine' 'rocksdb'
                          '--console'
-                         '--server.statistics' 'true' 
 					   )
                        # statistics false is new - check if it works with tests
                        #'--log.role' 'true'
 
-	local args_cp=( '--server.statistics' 'true'
-					'--log.level' 'INFO'
-					'--server.threads' '5'
-				  )
-                  #'--server.statistics' 'true' 
-	local port_agency=28356	
-	local port_primary=32984
+	#local args_cp=( '--server.statistics' 'true'
+	#				'--log.level' 'INFO'
+	#				'--server.threads' '5'
+	#			  )
+	local port_agency=28356
+	local port_primary1=32984
+	local port_primary2=32985
 	local port_coordinator=32885
 
     local tests=""
@@ -218,7 +219,7 @@ suite_local_cluster(){
         ;;
         0)
 			args_local=( '--server.endpoint' "tcp://[::]:$port_agency"
-			  		   '--database.directory' 'cluster/data-agency'
+			  		   '--database.directory' 'tmux_cluster/data-agency'
 			  		   '--javascript.app-path' './js/apps'
 			  		   '--javascript.v8-contexts' '1'
 			  		   '--agency.activate' 'true'
@@ -235,35 +236,47 @@ suite_local_cluster(){
 			)
         ;;
         1)
-            mkdir -p cluster/apps-primary
-			args_local=( '--server.endpoint' "tcp://[::]:$port_primary"
-			  		   '--database.directory' 'cluster/data-primary'
-    		  		   '--javascript.app-path' 'cluster/apps-primary'
+            mkdir -p tmux_cluster/apps-primary1
+			args_local=( '--server.endpoint' "tcp://[::]:$port_primary1"
+			  		   '--database.directory' 'tmux_cluster/data-primary1'
+    		  		   '--javascript.app-path' 'tmux_cluster/apps-primary1'
 			  		   '--cluster.agency-endpoint' "tcp://[::]:$port_agency"
-			  		   '--cluster.my-address' "tcp://[::1]:$port_primary"
+			  		   '--cluster.my-address' "tcp://[::1]:$port_primary1"
     		  		   '--cluster.my-role' 'PRIMARY'
-    		  		   '--log.file' 'cluster/primary.log'
+    		  		   '--log.file' 'tmux_cluster/primary1.log'
 			)
 			args_local+=( "${args_cp[@]}" )
         ;;
         2)
-            mkdir -p cluster/apps-coordinator
-			args_local=( '--server.endpoint' "tcp://[::]:$port_coordinator"
-			  		   '--database.directory' 'cluster/data-coordinator'
-			  		   '--javascript.app-path' 'cluster/apps-coordinator'
+            mkdir -p tmux_cluster/apps-primary2
+			args_local=( '--server.endpoint' "tcp://[::]:$port_primary2"
+			  		   '--database.directory' 'tmux_cluster/data-primary2'
+    		  		   '--javascript.app-path' 'tmux_cluster/apps-primary2'
 			  		   '--cluster.agency-endpoint' "tcp://[::]:$port_agency"
-			  		   '--cluster.my-address' "tcp://[::1]:$port_coordinator"
-			  		   '--cluster.my-role' 'COORDINATOR'
-			  		   '--log.file' 'cluster/coordinator.log'
+			  		   '--cluster.my-address' "tcp://[::1]:$port_primary2"
+    		  		   '--cluster.my-role' 'PRIMARY'
+    		  		   '--log.file' 'tmux_cluster/primary2.log'
 			)
 			args_local+=( "${args_cp[@]}" )
         ;;
         3)
+            mkdir -p tmux_cluster/apps-coordinator
+			args_local=( '--server.endpoint' "tcp://[::]:$port_coordinator"
+			  		   '--database.directory' 'tmux_cluster/data-coordinator'
+			  		   '--javascript.app-path' 'tmux_cluster/apps-coordinator'
+			  		   '--cluster.agency-endpoint' "tcp://[::]:$port_agency"
+			  		   '--cluster.my-address' "tcp://[::1]:$port_coordinator"
+			  		   '--cluster.my-role' 'COORDINATOR'
+			  		   '--log.file' 'tmux_cluster/coordinator.log'
+			)
+			args_local+=( "${args_cp[@]}" )
+        ;;
+        4)
             echo "./build/bin/arangosh --server.endpoint tcp://[::]:$port_coordinator"
             return
         ;;
-        4)
-            echo "sudo ngrep -W byline -d lo port $port_agency or port $port_primary or port $port_coordinator"
+        5)
+            echo "# sudo ngrep -W byline -d lo port $port_agency or port $port_primary1 or port $port_primary2 or port $port_coordinator"
             return
         ;;
         *)
@@ -310,7 +323,7 @@ spawn_panes(){
     if ((cols > 1)); then
         local count=$((rows - 1))
         while ((count >= 0)); do
-            tmux select-pane -t $session_name.$count || die "could not select pane $session_name.$count" 
+            tmux select-pane -t $session_name.$count || die "could not select pane $session_name.$count"
             tmux split-window -h -p 50
             (( count-- ))
         done
